### ISSUE TITLE
Move to flycheck org

### ISSUE THREAD

**Issue by jcs090218** [jcs-elpa/flycheck-deno#1]
Hi, @cpitclaudel!

I know you commented https://github.com/emacs-grammarly/flycheck-grammarly/issues/6#issuecomment-775732379, but since I am maintaining package `flycheck-google-cpplint` in the org. Can I transfer a few repos to the org?

- https://github.com/jcs-elpa/flycheck-deno (this repo)
- https://github.com/emacs-eask/flycheck-eask

It really helps me organize my projects and knowing where I should look up the package repo. And of course, I am maintaining these packages so you don't have to worry about the maintainer.

LMKWYT?

**Comment by cpitclaudel** [comment]
Sounds good to me!
And I had a quick look at the packages — they look good!

**Comment by cpitclaudel** [comment]
(Thanks for all your work, btw ^^)

**Comment by cpitclaudel** [comment]
Do you have the rights to transfer the repos to the org?

**Comment by jcs090218** [comment]
Yes, I can transfer it! (just transferred the two repos)

However, I've lost permission to those repos! Can you help me with this? And thank you!! ❤️

**Comment by cpitclaudel** [comment]
Done, I think!

**Comment by jcs090218** [comment]
Thank you very much! :D
